### ISSUE TITLE
[meta] Finalize the project

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/iSparrowRecord#8]
**What's the overarching idea and why is this additional feature necessary?**
`iSparrowRecord` needs to be set up in such a way that it can be run autonomously on a machine. Therefore, a number of things need to happen in order to make it runable, configure it, add interface capability and so on. 

**Describe into what individual steps/features your suggestion decays, and outline their basic ideas in one sentence each**

Functionality:  
- [x] add run script #3 
- [x] add small CLI  #7 
- [x] add installation/packaging stuff #10  
- [x] dockerize `iSparrowData` #18 

Maintenance: 
- [ ] add sphinx documentation 
- [x] add coverage report for tests and include min coverage for test acceptance
- [ ] add doctests
- [ ] add readme #11 
- [ ] 
Bug: 
- [ ] fix #12 

Improvements (optional): 
- [ ] improve cli #19 
- [x] add workflow to create container image when pypi release is made #20 
- [ ] add workflow for automatically generating releases  #15
